CREATE TABLE Carrito (
    CarritoID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PersonaID UNIQUEIDENTIFIER NOT NULL,
    Estado BIT NOT NULL DEFAULT 0,
    CodigoPromocionID UNIQUEIDENTIFIER,
    FOREIGN KEY (CodigoPromocionID) REFERENCES CodigosPromocion(CodigoPromocionID),
    FOREIGN KEY (PersonaID) REFERENCES Personas(Id)
);
