CREATE TABLE Empleado (
    EmpleadoID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UsuarioID UNIQUEIDENTIFIER NOT NULL,
    Especialidad VARCHAR(100) NOT NULL,
    FOREIGN KEY (UsuarioID) REFERENCES Personas(Id)
);