CREATE TABLE Expediente (
    ExpedienteID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    MascotaID UNIQUEIDENTIFIER NOT NULL,
    Diagnostico VARCHAR(200) NOT NULL
    FOREIGN KEY (MascotaID) REFERENCES Mascota(MascotaID)
);
