CREATE TABLE Productos (
    ProductoID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    CódigoProducto VARCHAR(50) NOT NULL,
    Nombre VARCHAR(100) NOT NULL,
    Categoria VARCHAR(100) NOT NULL,
    Presentacion VARCHAR(50) NOT NULL,
    Precio DECIMAL(10, 2) NOT NULL,
    Cantidad INT NOT NULL,
    StockID UNIQUEIDENTIFIER NOT NULL,
    Descripcion TEXT NOT NULL,
    Imagen VARCHAR(255) NOT NULL,
    FOREIGN KEY (StockID) REFERENCES Stock(StockID)
);