CREATE TABLE RegistroCitas (
    CitaID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    FechaHora DATETIME NOT NULL,
    Dueno VARCHAR(100) NOT NULL,
    MascotaID UNIQUEIDENTIFIER NULL,  
    Motivo VARCHAR(MAX) NOT NULL,
    VeterinarioAsignadoID UNIQUEIDENTIFIER NULL,
    PersonaID UNIQUEIDENTIFIER NULL,  
    FOREIGN KEY (VeterinarioAsignadoID) REFERENCES Empleado(EmpleadoID),
    FOREIGN KEY (MascotaID) REFERENCES Mascota(MascotaID),  
    FOREIGN KEY (PersonaID) REFERENCES Personas(Id)  
);
